---
- hosts: all
  gather_facts: false

  vars_prompt:
    - name: username
      prompt: 'Enter ssh user name'
      private: no
    - name: password
      prompt: 'Enter ssh user password'

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  tasks:
  - name: run ping
    ping:
